name: Update Directory Tree in README

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate directory tree and update README
        uses: andreasbm/readme-tree@v1.0.2
        with:
          path: '.'
          readme-path: 'README.md'

      - name: Ensure Git is installed
        run: sudo apt-get update && sudo apt-get install -y git

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add README.md
          git commit -m 'chore: update directory tree in README [skip ci]' || echo "No changes to commit"
          git push
